---
name: common_lint_slim
run-name: Lint Project

on:
  merge_group:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4.2.2
       with:
         # Get all history to be able to identify changed files
         fetch-depth: 0
          
     - name: Run Super Linter
       uses: super-linter/super-linter/slim@v7.2.1
       env:
         DEFAULT_BRANCH: ${{ github.base_ref }}
         GITHUB_TOKEN: ${{ github.token }}
         VALIDATE_ALL_CODEBASE: false
